## Importing Libraries

In [ ]:
import pandas as pd

In [2]:
import requests

## Code For Fetching The Data

In [3]:
final=pd.DataFrame()

for j in range(1,501):
    
    response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(j)).json()
    
    popularity=[]
    vote_count=[]
    original_language=[]
    title=[]
    vote_average=[]
    overview=[]
    release_date=[]


    for i in response['results']:

        popularity.append(i['popularity'])
        vote_count.append(i['vote_count'])
        original_language.append(i['original_language'])
        title.append(i['title'])
        vote_average.append(i['vote_average'])
        overview.append(i['overview'])
        try:
          release_date.append(i['release_date'])
        except: 
          release_date.append('NAN')

    d={'title':title, 'overview':overview, 'original_language':original_language, 'release_date':release_date, 'popularity':popularity, 'vote_count':vote_count, 'vote_average':vote_average}

    df=pd.DataFrame(d)
    
    final=final.append(df, ignore_index=True)

In [4]:
final

,title,overview,original_language,release_date,popularity,vote_count,vote_average
0,Ad Astra,"The near future, a time when both hope and har...",en,2019-09-17,501.143,2840,5.9
1,Ant-Man,Armed with the astonishing ability to shrink i...,en,2015-07-14,292.090,13604,7.1
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2020-01-15,264.191,2456,7.1
3,Bloodshot,"After he and his wife are murdered, marine Ray...",en,2020-03-05,263.434,1314,7.2
4,The Twilight Saga: Eclipse,Bella once again finds herself surrounded by d...,en,2010-06-23,238.860,5676,6.1
5,Birds of Prey (and the Fantabulous Emancipatio...,"Harley Quinn joins forces with a singer, an as...",en,2020-02-05,203.798,2598,7.1
6,Blood Father,An ex-con reunites with his estranged wayward ...,en,2016-08-11,188.131,944,6.1
7,Underwater,After an earthquake destroys their underwater ...,en,2020-01-08,181.725,558,6.5
8,Jumanji: The Next Level,As the gang return to Jumanji to rescue one of...,en,2019-12-04,165.273,2945,6.8
9,The Platform,"A mysterious place, an indescribable prison, a...",es,2019-11-08,162.227,1879,7.2
10,Star Wars: The Rise of Skywalker,The surviving Resistance faces the First Order...,en,2019-12-18,157.937,3781,6.5
11,Onward,"In a suburban fantasy world, two teenage elf b...",en,2020-02-29,155.892,930,8.0
12,Transformers: The Last Knight,"Autobots and Decepticons are at war, with huma...",en,2017-06-16,154.093,3749,6.0
13,Sonic the Hedgehog,Based on the global blockbuster videogame fran...,en,2020-02-12,150.685,2035,7.4
14,30 Days of Night: Dark Days,"After surviving the incidents in Barrow, Alask...",en,2010-10-04,137.117,261,4.8
15,The Invisible Man,When Cecilia's abusive ex takes his own life a...,en,2020-02-26,132.614,1221,7.2
16,Live Free or Die Hard,"John McClane is back and badder than ever, and...",en,2007-06-20,120.750,3713,6.5
17,John Wick,Ex-hitman John Wick comes out of retirement to...,en,2014-10-22,116.853,12133,7.2
18,Emma.,"In 1800s England, a well-meaning but selfish y...",en,2020-02-13,116.424,143,7.1
19,Cold Blood,A legendary but retired hit man lives in peace...,fr,2019-05-15,116.316,117,5.1
20,Cars,"Lightning McQueen, a hotshot rookie race car d...",en,2006-06-08,113.883,8992,6.8
21,Jurassic World: Fallen Kingdom,Three years after the demise of Jurassic World...,en,2018-06-06,107.504,7217,6.5
22,Tales from the Darkside: The Movie,The first segment features an animated mummy s...,en,1990-05-03,107.201,173,6.1
23,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",en,2013-08-07,345.601,3537,5.9
24,Miracle in Cell No. 7,"Separated from his daughter, a father with an ...",tr,2019-10-10,104.599,1573,8.4
25,Atlantis: The Lost Empire,The world's most highly qualified crew of arch...,en,2001-06-02,104.185,2985,6.9
26,Frozen II,"Elsa, Anna, Kristoff and Olaf head far into th...",en,2019-11-20,104.173,3599,7.1
27,Joker,"During the 1980s, a failed stand-up comedian i...",en,2019-10-02,101.751,10879,8.2
28,A Rainy Day in New York,Two young people arrive in New York to spend a...,en,2019-07-26,101.707,781,6.6
29,Lara Croft: Tomb Raider - The Cradle of Life,Lara Croft ventures to an underwater temple in...,en,2003-07-21,150.899,2895,5.7
...,...,...,...,...,...,...,...
9970,Till Luck Do Us Part 2,"After all the trouble in the first film, Tino ...",pt,2013-12-27,7.830,171,5.7
9971,Space Buddies,"B-Dawg, Mudbud, Budderball, and all the rest o...",en,2009-02-02,7.830,88,5.1
9972,Tetro,Bennie travels to Buenos Aires to find his lon...,en,2009-06-11,7.830,100,6.8
9973,Blackmail,"London, 1929. Frank Webber, a very busy Scotla...",en,1929-07-28,7.830,101,6.7
9974,Oliver Twist,When 9-year-old orphan Oliver Twist dares to a...,en,1948-06-28,7.828,100,7.4
9975,High Heels,High Heels is a murder mystery comedy centerin...,es,1991-10-23,7.828,190,7.2
9976,Always a Bridesmaid,"Tired of always being the bridesmaid, Corina J...",en,2019-09-28,7.827,2,5.8
9977,Back to School,Two adults go to their middle school reunion i...,fr,2019-08-30,7.827,164,5.3
9978,You May Not Kiss the Bride,An unassuming pet photographer is thrown into ...,en,2011-04-03,7.827,115,5.9
9979,Dangerous Days: Making 'Blade Runner',The definitive 3½-hour documentary about the t...,en,2007-12-18,7.827,36,7.9
9980,An Empress and the Warriors,"After the death of her father, a woman is forc...",zh,2008-02-09,7.827,58,6.1
9981,"A Genius, Two Friends, and an Idiot","Three rogues set out to rob $300,000 from an I...",it,1975-12-16,7.827,76,6.5
9982,The Lodger: A Story of the London Fog,London. A mysterious serial killer brutally mu...,en,1927-02-14,7.827,122,7.2
9983,Five,A young man paying the rent for himself and hi...,fr,2016-03-30,7.825,625,7.2
9984,Iris,True story of the lifelong romance between nov...,en,2001-12-14,7.825,103,6.4
9985,An Open Secret,An investigation into accusations of teenagers...,en,2015-06-05,7.824,33,7.4
9986,Cymbeline,War erupts between dirty cops and outlaw biker...,en,2014-09-03,7.824,65,3.8
9987,Going My Way,Youthful Father Chuck O'Malley led a colorful ...,en,1944-05-15,7.824,73,7.0
9988,Lifeboat,"During World War II, a small group of survivor...",en,1944-01-28,7.824,219,7.5
9989,Stir Crazy,"New Yorkers, Skip Donahue and Harry Monroe hav...",en,1980-12-12,7.823,225,6.6
9990,Keeping Mum,A pastor preoccupied with writing the perfect ...,en,2005-12-02,7.823,308,6.6
9991,The Double,The mysterious murder of a US senator bearing ...,en,2011-10-27,7.822,391,5.8
9992,Dave Chappelle: Deep in the Heart of Texas,Comedy icon Dave Chappelle makes his triumphan...,en,2017-03-21,7.821,116,8.0
9993,Michael Moore in TrumpLand,Oscar-winner Michael Moore dives right into ho...,en,2016-10-18,7.821,60,6.2
9994,The Last Face,"Miguel, a heroic Spanish doctor, puts himself ...",en,2016-05-20,7.821,124,5.6
9995,Too Big to Fail,An intimate look at the epochal financial cris...,en,2011-05-22,7.821,114,7.0
9996,The Hard Way,Seeking to raise his credibility as an actor a...,en,1991-03-08,7.821,208,6.2
9997,Wonderland,"On the afternoon of July 1, 1981, Los Angeles ...",en,2003-10-23,7.821,146,6.2
9998,Pink,Deepak is a lawyer suffering from bipolar diso...,hi,2016-09-16,7.820,100,7.5
9999,Ice Sculpture Christmas,After starting her first job at a country club...,en,2015-11-07,7.820,47,5.9

In [5]:
final.to_csv('TMDb') ## V_1